name: Scala CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up sbt
        uses: sbt/setup-sbt@v1

      - name: Compile Scala code
        run: sbt compile

      # Check Scala formatting
      - name: Check Scala formatting
        run: sbt scalafmtCheck


      - name: Run sbt tests
        run: sbt test